web-app-asp-net-mvc-pdf/Models/Entities/Lesson.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web_app_asp_net_mvc_pdf.Extensions;
using web_app_asp_net_mvc_pdf.Models.Attributes;

namespace web_app_asp_net_mvc_pdf.Models
{
    public class Lesson
    {
        /// <summary>
        /// Id
        /// </summary> 
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Порядковый номер пары в расписании
        /// </summary>    
        [Required]
        [Display(Name = "Номер пары в расписании", Order = 1)]
        [Range(1, 8, ErrorMessage = "Недопустимое значение")]
        public int Number { get; set; }

        /// <summary>
        /// Название пары
        /// </summary>    
        ///[Required]
        ///[Display(Name = "Пара", Order = 2)]
        ///public String Name { get; set; }

        /// <summary>
        /// Группа, у которой будет пара
        /// </summary> 
        [ScaffoldColumn(false)]
        public virtual ICollection<Group> Groups { get; set; }

        [ScaffoldColumn(false)]
        public List<int> GroupIds { get; set; }

        [Display(Name = "Группы", Order = 70)]
        [UIHint("MultipleDropDownList")]
        [TargetProperty("GroupIds")]
        [NotMapped]
        public IEnumerable<SelectListItem> GroupDictionary
        {
            get
            {
                var db = new TimetableContext();
                var query = db.Groups;

                if (query != null)
                {
                    var Ids = query.Where(s => s.Lessons.Any(ss => ss.Id == Id)).Select(s => s.Id).ToList();
                    var dictionary = new List<SelectListItem>();
                    dictionary.AddRange(query.ToSelectList(c => c.Id, c => $"{c.GroupName}", c => Ids.Contains(c.Id)));
                    return dictionary;
                }

                return new List<SelectListItem> { new SelectListItem { Text = "", Value = "" } };
            }
        }

        /// <summary>
        /// Преподаватель
        /// </summary> 
        [ScaffoldColumn(false)]
        public int TeacherId { get; set; }
        [ScaffoldColumn(false)]
        public virtual Teacher Teacher { get; set; }
        [Display(Name = "Преподаватель", Order = 50)]
        [UIHint("DropDownList")]
        [TargetProperty("TeacherId")]
        [NotMapped]
        public IEnumerable<SelectListItem> TeacherDictionary
        {
            get
            {
                var db = new TimetableContext();
                var query = db.Teachers;

                if (query != null)
                {
                    var dictionary = new List<SelectListItem>();
                    dictionary.AddRange(query.OrderBy(d => d.Name).ToSelectList(c => c.Id, c => c.Name, c => c.Id == TeacherId));
                    return dictionary;
                }

                return new List<SelectListItem> { new SelectListItem { Text = "", Value = "" } };
            }
        }

        /// <summary>
        /// Дисциплина
        /// </summary> 
        [ScaffoldColumn(false)]
        public int DisciplineId { get; set; }
        [ScaffoldColumn(false)]
        public virtual Discipline Discipline { get; set; }
        [Display(Name = "Дисциплина", Order = 2)]
        [UIHint("RadioList")]
        [TargetProperty("DisciplineId")]
        [NotMapped]
        public IEnumerable<SelectListItem> DisciplineDictionary
        {
            get
            {
                var db = new TimetableContext();
                var query = db.Disciplines;

                if (query != null)
                {
                    var dictionary = new List<SelectListItem>();
                    dictionary.AddRange(query.OrderBy(d => d.Name).ToSelectList(c => c.Id, c => c.Name, c => c.Id == DisciplineId));
                    return dictionary;
                }

                return new List<SelectListItem> { new SelectListItem { Text = "", Value = "" } };
            }
        }





    }
}

web-app-asp-net-mvc-pdf/Controllers/DisciplinesController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using web_app_asp_net_mvc_pdf.Models;

namespace web_app_asp_net_mvc_pdf.Controllers
{
    public class DisciplinesController : Controller
    {
        private readonly string _key = "123456Qq";

        [HttpGet]
        public ActionResult Index()
        {
            var db = new TimetableContext();
            var disciplines = db.Disciplines.ToList();

            return View(disciplines);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var discipline = new Discipline();
            return View(discipline);
        }

        [HttpPost]
        public ActionResult Create(Discipline model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var db = new TimetableContext();
            if (model.Key != _key)
                ModelState.AddModelError("Key", "Ключ для создания/изменения записи указан не верно");
            if (!ModelState.IsValid)
                return View(model);
            db.Disciplines.Add(model);
            db.SaveChanges();

            return RedirectPermanent("/Disciplines/Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var db = new TimetableContext();
            var discipline = db.Disciplines.FirstOrDefault(x => x.Id == id);
            if (discipline == null)
                return RedirectPermanent("/Disciplines/Index");

            db.Disciplines.Remove(discipline);
            db.SaveChanges();

            return RedirectPermanent("/Disciplines/Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var db = new TimetableContext();
            var discipline = db.Disciplines.FirstOrDefault(x => x.Id == id);
            if (discipline == null)
                return RedirectPermanent("/Disciplines/Index");

            return View(discipline);
        }

        [HttpPost]
        public ActionResult Edit(Discipline model)
        {
            var db = new TimetableContext();
            var discipline = db.Disciplines.FirstOrDefault(x => x.Id == model.Id);
            if (discipline == null)
                ModelState.AddModelError("Id", "Дисциплина не найдена");
            if (model.Key != _key)
                ModelState.AddModelError("Key", "Ключ для создания/изменения записи указан не верно");
            if (!ModelState.IsValid)
                return View(model);

            MappingDiscipline(model, discipline, db);

            db.Entry(discipline).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectPermanent("/Disciplines/Index");
        }

        private void MappingDiscipline(Discipline sourse, Discipline destination, TimetableContext db)
        {
            destination.Name = sourse.Name;
            destination.DisciplineGoal = sourse.DisciplineGoal;
            destination.DisciplineObjectives = sourse.DisciplineObjectives;
            destination.MainSections = sourse.MainSections;
            destination.Key = sourse.Key;


        }

    }
}

web-app-asp-net-mvc-pdf/Controllers/LessonsController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Rotativa;
using web_app_asp_net_mvc_pdf.Models;

namespace web_app_asp_net_mvc_pdf.Controllers
{
    public class LessonsController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var db = new TimetableContext();
            var lessons = db.Lessons.ToList();

            return View(lessons);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var lesson = new Lesson();
            return View(lesson);
        }

        [HttpPost]
        public ActionResult Create(Lesson model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var db = new TimetableContext();

            if (model.GroupIds != null && model.GroupIds.Any())
            {
                var group = db.Groups.Where(s => model.GroupIds.Contains(s.Id)).ToList();
                model.Groups = group;
            }

            db.Lessons.Add(model);
            db.SaveChanges();

            return RedirectPermanent("/Lessons/Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var db = new TimetableContext();
            var lesson = db.Lessons.FirstOrDefault(x => x.Id == id);
            if (lesson == null)
                return RedirectPermanent("/Lessons/Index");

            db.Lessons.Remove(lesson);
            db.SaveChanges();

            return RedirectPermanent("/Lessons/Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var db = new TimetableContext();
            var lesson = db.Lessons.FirstOrDefault(x => x.Id == id);
            if (lesson == null)
                return RedirectPermanent("/Lessons/Index");

            return View(lesson);
        }

        [HttpPost]
        public ActionResult Edit(Lesson model)
        {
            var db = new TimetableContext();
            var lesson = db.Lessons.FirstOrDefault(x => x.Id == model.Id);
            if (lesson == null)
                ModelState.AddModelError("Id", "Пара не найдена");

            if (!ModelState.IsValid)
                return View(model);

            MappingLesson(model, lesson, db);

            db.Entry(lesson).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectPermanent("/Lessons/Index");
        }

        private void MappingLesson(Lesson sourse, Lesson destination, TimetableContext db)
        {
            destination.Number = sourse.Number;
            destination.DisciplineId = sourse.DisciplineId;
            destination.Discipline = sourse.Discipline;
            destination.TeacherId = sourse.TeacherId;
            destination.Teacher = sourse.Teacher;



            if (destination.Groups != null)
                destination.Groups.Clear();

            if (sourse.GroupIds != null && sourse.GroupIds.Any())
                destination.Groups = db.Groups.Where(s => sourse.GroupIds.Contains(s.Id)).ToList();
        }

        [HttpGet]
        public ActionResult GetImage(int id)
        {
            var db = new TimetableContext();
            var image = db.TeacherImages.FirstOrDefault(x => x.Id == id);
            if (image == null)
            {
                FileStream fs = System.IO.File.OpenRead(Server.MapPath(@"~/Content/Images/not-foto.png"));
                byte[] fileData = new byte[fs.Length];
                fs.Read(fileData, 0, (int)fs.Length);
                fs.Close();

                return File(new MemoryStream(fileData), "image/jpeg");
            }

            return File(new MemoryStream(image.Data), image.ContentType);
        }

        [HttpGet]
        public ActionResult Detail(int id)
        {
            var db = new TimetableContext();
            var lesson = db.Lessons.FirstOrDefault(x => x.Id == id);
            if (lesson == null)
                return RedirectPermanent("/Lessons/Index");

            return View(lesson);
        }

        [HttpGet]
        public ActionResult Pdf(int id)
        {
            var db = new TimetableContext();
            var lesson = db.Lessons.FirstOrDefault(x => x.Id == id);
            if (lesson == null)
                return RedirectPermanent("/Lessons/Index");

            var pdf = new ViewAsPdf("Pdf", lesson);
            var data = pdf.BuildFile(this.ControllerContext);


            return File(new MemoryStream(data), "application/pdf", "document.pdf");
        }
    }
}

web-app-asp-net-mvc-pdf/Views/Lessons/Create.cshtml
@using web_app_asp_net_mvc_pdf.Models
@model Lesson

<fieldset>
    <legend>Пожалуйста, заполните необходимые поля</legend>
    @using (Html.BeginForm("Create", "Lessons", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.EditorForModel()
        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Lessons", null, new { @class = "btn btn-danger" })
        
    }
</fieldset>

web-app-asp-net-mvc-pdf/Views/Lessons/Detail.cshtml
@using web_app_asp_net_mvc_pdf.Models
@model Lesson


<table class="table align-middle " style="text-align:center">
    <tbody>
        <tr>

            <td >
                <br />
                <h1><u>@Model.Discipline.Name</u></h1>
            </td>
        </tr>

        <tr>
            <td colspan="2">
                <h3>Аннотация</h3>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <p>
                    <span><b>Цель дисциплины</b></span>
                    <span><pre style="width: auto; white-space: pre-wrap;">@Model.Discipline.DisciplineGoal</pre></span>
                </p>
                <p>
                    <span><b>Задачи дисциплины</b></span>
                    <span><pre style="width: auto; white-space: pre-wrap;">@Model.Discipline.DisciplineObjectives</pre></span>
                </p>
                <p>
                    <span><b>Основные разделы</b></span>
                    <span><pre style="width: auto; white-space: pre-wrap;">@Model.Discipline.MainSections</pre></span>
                </p>
            </td>
        </tr>

    </tbody>
</table>


@Html.ActionLink("На главную", "Index", "Lessons", null, new { @class = "btn btn-outline-dark" })

@Html.ActionLink("Изменить дисциплины", "Index", "Disciplines", null, new { @class = "btn btn-outline-dark" })

<a href="/Lessons/Pdf/@Model.Id" class="btn btn-outline-dark" title="Скачать pdf" target="_blank">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-pdf" viewBox="0 0 16 16">
        <path d="M4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4zm0 1h8a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1z" />
        <path d="M4.603 12.087a.81.81 0 0 1-.438-.42c-.195-.388-.13-.776.08-1.102.198-.307.526-.568.897-.787a7.68 7.68 0 0 1 1.482-.645 19.701 19.701 0 0 0 1.062-2.227 7.269 7.269 0 0 1-.43-1.295c-.086-.4-.119-.796-.046-1.136.075-.354.274-.672.65-.823.192-.077.4-.12.602-.077a.7.7 0 0 1 .477.365c.088.164.12.356.127.538.007.187-.012.395-.047.614-.084.51-.27 1.134-.52 1.794a10.954 10.954 0 0 0 .98 1.686 5.753 5.753 0 0 1 1.334.05c.364.065.734.195.96.465.12.144.193.32.2.518.007.192-.047.382-.138.563a1.04 1.04 0 0 1-.354.416.856.856 0 0 1-.51.138c-.331-.014-.654-.196-.933-.417a5.716 5.716 0 0 1-.911-.95 11.642 11.642 0 0 0-1.997.406 11.311 11.311 0 0 1-1.021 1.51c-.29.35-.608.655-.926.787a.793.793 0 0 1-.58.029zm1.379-1.901c-.166.076-.32.156-.459.238-.328.194-.541.383-.647.547-.094.145-.096.25-.04.361.01.022.02.036.026.044a.27.27 0 0 0 .035-.012c.137-.056.355-.235.635-.572a8.18 8.18 0 0 0 .45-.606zm1.64-1.33a12.647 12.647 0 0 1 1.01-.193 11.666 11.666 0 0 1-.51-.858 20.741 20.741 0 0 1-.5 1.05zm2.446.45c.15.162.296.3.435.41.24.19.407.253.498.256a.107.107 0 0 0 .07-.015.307.307 0 0 0 .094-.125.436.436 0 0 0 .059-.2.095.095 0 0 0-.026-.063c-.052-.062-.2-.152-.518-.209a3.881 3.881 0 0 0-.612-.053zM8.078 5.8a6.7 6.7 0 0 0 .2-.828c.031-.188.043-.343.038-.465a.613.613 0 0 0-.032-.198.517.517 0 0 0-.145.04c-.087.035-.158.106-.196.283-.04.192-.03.469.046.822.024.111.054.227.09.346z" />
    </svg>
</a>

<hr />


<sub><i>Описание может быть не точным</i></sub>

web-app-asp-net-mvc-pdf/Views/Lessons/Edit.cshtml
@using web_app_asp_net_mvc_pdf.Models
@model Lesson

<fieldset>
    <legend>Пожалуйста, заполните необходимые поля</legend>
    @using (Html.BeginForm("Edit", "Lessons", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary()
        @Html.EditorForModel()
        
        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Lessons", null, new { @class = "btn btn-danger" })
    }
</fieldset>

web-app-asp-net-mvc-pdf/Views/Lessons/Index.cshtml
@using web_app_asp_net_mvc_pdf.Models
@using web_app_asp_net_mvc_pdf.Extensions
@model List<Lesson>

@{
    string controllerName = "Lessons";
}
<br>
<h1><b>Расписание</b></h1>

<br>

<table class="table table-hover table-bordered border-dark  align-middle " style="text-align:center">
    <thead>
        <tr class="bg-secondary">
            <th>
                Номер пары
            </th>
            <th>
                Дисциплина
            </th>
            <th>
                Группа(ы)
            </th>
            <th>
                Преподаватель
            </th>
            <th>
                Фото преподавателя
            </th>
            <th>
                Действия
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var lesson in Model)
        {
            <tr >
                <td >
                    @lesson.Number
                </td>
                <td>
                    <a href="/Lessons/Detail/@lesson.Id">@lesson.Discipline.Name</a>

                </td>
                <td>
                    @string.Join(", ", lesson.Groups.Select(x => $"{x.GroupName}"))
                </td>
                <td>
                    @lesson.Teacher.Name
                </td>
                <td>
                    <img src="/Teachers/GetImage/@lesson.TeacherId"class="rounded" style="max-width: 50px; max-height: 100px;" />
                </td>
                <td>
                    <div class="btn-group mb-3, vertical-align:middle align-middle">
                        <a href="/@controllerName/Edit/@lesson.Id" class="btn btn-outline-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                            </svg>
                        </a>
                        <a href="/@controllerName/Delete/@lesson.Id" class="btn btn-outline-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-backspace-fill" viewBox="0 0 16 16">
                                <path d="M15.683 3a2 2 0 0 0-2-2h-7.08a2 2 0 0 0-1.519.698L.241 7.35a1 1 0 0 0 0 1.302l4.843 5.65A2 2 0 0 0 6.603 15h7.08a2 2 0 0 0 2-2V3zM5.829 5.854a.5.5 0 1 1 .707-.708l2.147 2.147 2.146-2.147a.5.5 0 1 1 .707.708L9.39 8l2.146 2.146a.5.5 0 0 1-.707.708L8.683 8.707l-2.147 2.147a.5.5 0 0 1-.707-.708L7.976 8 5.829 5.854z" />
                            </svg>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<br>
<div class="btn-create" style="display: flex; justify-content: flex-end;">
    @Html.ActionLink("Добавить запись", "Create", controllerName, null, new { @class = "btn btn-outline-dark" })
</div>
 
<br>
<br>
<br>
<br>
<br>
<hr>
<footer>
    <dl>
        <dt>Дополнительная информация:</dt>
    </dl>
    <ol type="I">
        <li><h6><i>Данная работа сделана в ознакомительных целях</i></h6></li>
        <li><h6><i>Все люди вымышлены, а совпадения случайны</i></h6></li>
    </ol>

</footer>

web-app-asp-net-mvc-pdf/Views/Lessons/Pdf.cshtml
@using web_app_asp_net_mvc_pdf.Models
@model Lesson

@{
    Layout = null;
}

<html>
<head>
    <style>
    </style>
</head>

<body>



    <table class="table align-middle " style="text-align:center">
        <tbody>
            <tr>

                <td>
                    <br />
                    <h1><u>@Model.Discipline.Name</u></h1>
                </td>
            </tr>

            <tr>
                <td colspan="2">
                    <h3>Аннотация</h3>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <p>
                        <span><b>Цель дисциплины</b></span>
                        <span><pre style="width: auto; white-space: pre-wrap;">@Model.Discipline.DisciplineGoal</pre></span>
                    </p>
                    <p>
                        <span><b>Задачи дисциплины</b></span>
                        <span><pre style="width: auto; white-space: pre-wrap;">@Model.Discipline.DisciplineObjectives</pre></span>
                    </p>
                    <p>
                        <span><b>Основные разделы</b></span>
                        <span><pre style="width: auto; white-space: pre-wrap;">@Model.Discipline.MainSections</pre></span>
                    </p>
                </td>
            </tr>

        </tbody>
    </table>




    


    



</body>

</html>